### ISSUE TITLE
Add support for strongly typed event transformer

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-scala-analytics-sdk#15] opened 2016-08-11 08:04 UTC
The event transformer at the moment is essentially dynamic - it takes the JSONs it finds and does some lightweight reformatting to make them a bit more accessible within the event. It doesn't use the schemas for this as the correctness of the JSONs is implied by the fact they have made it through the pipeline

It would be possible to use the schemas to generate more strongly typed entities - for example, Scala case classes or Java POJOs. There is a crude way of doing this and a more sophisticated way:
1. The crude way is to duplicate the Iglu schemas you care about into your project and then run a generator process to make case classes
2. The more sophisticated way will be when Iglu server itself exposes a Maven repository containing artifacts for every schema you might want to pull into your project and work with in a strongly typed way

We'll probably start with the crude way, and prototype a strongly typed event transformer where you specify which entities you want to extract in your event which would be user-specific

(We have an AWS Lambda we use which does something similar but in a very non-generic way
looks for specific entities and turns them into case classes.)

**Comment by chuwy** [comment] 2018-12-18 15:40
Duplicate of https://github.com/snowplow/snowplow-scala-analytics-sdk/issues/15

**Closed by chuwy** 2018-12-18 15:40 UTC
